export const timeList = [
    { time: 6, notice: "" },
    { time: 7, notice: "" },
    { time: 8, notice: "" },
    { time: 9, notice: "" },
    { time: 10, notice: "" },
    { time: 11, notice: "" },
    { time: 12, notice: "" },
    { time: 13, notice: "" },
    { time: 14, notice: "" },
    { time: 15, notice: "" },
    { time: 16, notice: "" },
    { time: 17, notice: "" },
    { time: 18, notice: "" },
    { time: 19, notice: "" },
    { time: 20, notice: "" },
    { time: 21, notice: "" },
    { time: 22, notice: "" },
];